server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 2211
  jpa:
    hibernate:
            ddl-auto: update
#      ddl-auto: create
    show-sql: true
    open-in-view: true
  sql:
    init:
      mode: never
  data:
    rest:
      base-path: /api

